import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { sendOpsSlack } from '@/lib/slack'
import { weekMonday } from '@/lib/media'
import type { MediaWorkOrder } from '@/types'

// Samuel clicks "Notify Wilson" once he's done the weekly review. Sends ONE Slack
// summary of this week's outstanding (todo) work orders — never a ping per review.
export async function POST() {
  const supabase = await createClient()
  const week = weekMonday()

  // Work orders generated by this week's reviews that Wilson hasn't started yet.
  const { data: reviews } = await supabase.from('media_reviews').select('id').eq('week', week)
  const reviewIds = (reviews ?? []).map(r => r.id)
  if (!reviewIds.length) return NextResponse.json({ sent: false, count: 0 })

  const { data, error } = await supabase
    .from('media_work_orders')
    .select('*, client:clients(id, name, business_name)')
    .in('review_id', reviewIds)
    .eq('status', 'todo')
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  const orders = (data ?? []) as MediaWorkOrder[]
  if (!orders.length) return NextResponse.json({ sent: false, count: 0 })

  // Roll up by client so a client needing 2 ads is one line, not two.
  const byClient: Record<string, { name: string; count: number }> = {}
  for (const o of orders) {
    const name = o.client?.name ?? 'Client'
    ;(byClient[name] ??= { name, count: 0 }).count += 1
  }
  const lines = Object.values(byClient)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(c => `• ${c.name} — ${c.count} ad${c.count > 1 ? 's' : ''}`)

  const total = orders.length
  await sendOpsSlack(
    `🎬 *Ad review complete* — ${total} new work order${total > 1 ? 's' : ''} for Wilson to produce:\n${lines.join('\n')}\n\nQueue: Command Center → Media Buying → Work Orders.`,
  )

  return NextResponse.json({ sent: true, count: total, clients: Object.keys(byClient).length })
}
